### ISSUE TITLE
Maintainer doesn't want to do anything even if he's jobless, has not rent to pay, and doesn't go to school.

### ISSUE THREAD

**Issue by Brandontam29** [yoman321/portfolio#5]
0 reponsibilities. 0 job while he used to work at Sail 8h/week. 0 school because it is summer. Spends all his time playing chess. Why did I even help him port this app into next. ff@15 rip google

**Comment by Brandontam29** [comment]
Will add label, will not fix.....

**Comment by yoman321** [comment]
job has been found
